"""Local document commands. The harness itself needs only the standard library."""
import argparse
import json
import os
from pathlib import Path
import signal
import subprocess
import sys

# Diagnostics must remain read-only even on a freshly installed consumer repo.
sys.dont_write_bytecode = True
from document_store import prepare_storage, safe_path

VERSION = '2.132.0'
BASE = '.operacao-local/docling'
WORKER = Path(__file__).with_name('docling_worker.py')


def runtime_python(runtime):
    return Path(runtime) / ('Scripts/python.exe' if os.name == 'nt' else 'bin/python')


def worker_environment(base, *, offline=True):
    base = Path(base).absolute()
    env = {k: v for k, v in os.environ.items()
           if k.upper() in ('PATH', 'SYSTEMROOT', 'WINDIR', 'PATHEXT')}
    for folder in ('cache', 'temp', 'home'):
        (base / folder).mkdir(parents=True, exist_ok=True)
    env.update(HOME=str(base / 'home'), USERPROFILE=str(base / 'home'),
               LOCALAPPDATA=str(base / 'home'), APPDATA=str(base / 'home'),
               TEMP=str(base / 'temp'), TMP=str(base / 'temp'),
               PIP_CACHE_DIR=str(base / 'cache/pip'),
               HF_HOME=str(base / 'cache/huggingface'), TORCH_HOME=str(base / 'cache/torch'),
               XDG_CACHE_HOME=str(base / 'cache'), DOCLING_CACHE_DIR=str(base / 'cache/docling'),
               PIP_CONFIG_FILE=os.devnull, PIP_DISABLE_PIP_VERSION_CHECK='1',
               HF_HUB_DISABLE_TELEMETRY='1', DO_NOT_TRACK='1', PYTHONUTF8='1')
    if offline:
        env.update(HF_HUB_OFFLINE='1', TRANSFORMERS_OFFLINE='1')
    return env


def run_process(arguments, *, timeout, env):
    options = {'creationflags': subprocess.CREATE_NEW_PROCESS_GROUP} if os.name == 'nt' else {'start_new_session': True}
    with subprocess.Popen(arguments, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env, **options) as process:
        try:
            stdout, stderr = process.communicate(timeout=timeout)
        except subprocess.TimeoutExpired:
            if os.name == 'nt':
                subprocess.run(['taskkill', '/PID', str(process.pid), '/T', '/F'],
                               capture_output=True, timeout=15)
            else:
                os.killpg(process.pid, signal.SIGKILL)
            process.communicate()
            raise subprocess.TimeoutExpired(['docling-worker'], timeout) from None
        return subprocess.CompletedProcess(['docling-worker'], process.returncode, stdout, stderr)


def failed(code, state='failed'):
    return dict(state=state, warnings=[code], coverage={}, note_path=None)


def run_worker(source, output, runtime, profile='documents'):
    """Only local paths cross the worker boundary; never relay its stderr."""
    source, output, runtime = Path(source), Path(output), Path(runtime)
    executable = runtime_python(runtime)
    if not executable.is_file():
        return failed('runtime_missing', 'pending')
    output.mkdir(parents=True, exist_ok=False)
    request = output / 'request.json'
    request.write_text(json.dumps(dict(source=str(source.absolute()), output=str(output.absolute()),
                                       models=str((runtime.parent / 'models').absolute()), profile=profile)), encoding='utf-8')
    try:
        result = run_process([str(executable), str(WORKER), 'convert', str(request)], timeout=1800,
                             env=worker_environment(runtime.parent))
        if result.returncode:
            (output / 'error.log').write_bytes(result.stderr)
            return failed('conversion_failed')
        data = json.loads(result.stdout)
        if not isinstance(data, dict) or data.get('state') not in ('ready', 'partial', 'failed', 'unsupported'):
            return failed('invalid_worker_result')
        for current, directories, files in os.walk(output, followlinks=False):
            relative = Path(current).relative_to(output)
            for directory in directories:
                safe_path(output, relative / directory / '.probe')
            for name in files:
                safe_path(output, relative / name)
        if data['state'] in ('ready', 'partial') and not all((output / p).is_file() for p in ('content.md', 'document.json')):
            return failed('invalid_worker_result')
        # Trust only the protocol generated by our worker, not diagnostic text.
        return {key: data[key] for key in ('state', 'warnings', 'coverage', 'converter') if key in data}
    except subprocess.TimeoutExpired:
        return failed('conversion_timeout')
    except (OSError, ValueError):
        return failed('invalid_worker_result')
    finally:
        request.unlink(missing_ok=True)


def doctor(root):
    base = Path(root) / BASE
    executable = runtime_python(base / 'venv')
    if not executable.is_file():
        return failed('runtime_missing', 'pending')
    try:
        manifest = json.loads((base / 'environment.json').read_text(encoding='utf-8'))
        if manifest['docling'] != VERSION:
            return failed('runtime_version_mismatch')
        if not manifest['packages'].get('onnxruntime'):
            return failed('runtime_dependencies_missing', 'pending')
        for item in manifest['models']:
            path = safe_path(Path(root), Path(BASE) / 'models' / item['path'])
            if path.stat().st_size != item['size']:
                return failed('models_incomplete', 'pending')
        if not manifest['models']:
            return failed('models_incomplete', 'pending')
        result = subprocess.run([str(executable), str(WORKER), 'versions'],
                                capture_output=True, timeout=30)
        actual = json.loads(result.stdout)
        if result.returncode or actual['docling'] != VERSION or actual['packages'] != manifest['packages']:
            return failed('runtime_version_mismatch')
        return dict(state='ready', warnings=[], profile=manifest['profile'], docling=VERSION,
                    python=actual['python'], models=len(manifest['models']))
    except (OSError, ValueError, KeyError, TypeError, subprocess.TimeoutExpired):
        return failed('runtime_incomplete', 'pending')


def setup(root, profile='documents'):
    if profile != 'documents':
        raise ValueError('Unsupported profile.')
    root = Path(root).resolve(strict=True)
    prepare_storage(root)
    base = root / BASE
    for relative in ('venv/pyvenv.cfg', 'models/.probe', 'cache/.probe', 'temp/.probe', 'home/.probe',
                     'environment.json', 'setup.log'):
        safe_path(root, Path(BASE) / relative)
    if (base / 'environment.json').exists():
        result = doctor(root)
        if result['state'] != 'ready':
            raise ValueError('Existing runtime differs or is incomplete; inspect doctor before replacing it.')
        return result
    env = worker_environment(base, offline=False)
    executable = runtime_python(base / 'venv')
    commands = []
    installed = None
    packages = {}
    if executable.exists():
        probe = run_process([str(executable), str(WORKER), 'versions'], timeout=30, env=env)
        if probe.returncode:
            return failed('runtime_incomplete')
        existing = json.loads(probe.stdout)
        installed = existing['docling']
        packages = existing.get('packages', {})
        if installed not in (None, VERSION):
            return failed('runtime_version_mismatch')
    if not executable.exists():
        commands.append([sys.executable, '-m', 'venv', str(base / 'venv')])
    requirements = Path(__file__).resolve().parents[1] / 'requirements/docling.txt'
    if installed is None or not packages.get('onnxruntime'):
        commands.append([str(executable), '-m', 'pip', 'install', '-r', str(requirements)])
    commands.append([str(executable), str(WORKER), 'prepare', str(base / 'models')])
    for command in commands:
        result = run_process(command, timeout=1800, env=env)
        with (base / 'setup.log').open('ab') as log:
            log.write(result.stdout + result.stderr)
        if result.returncode:
            return failed('setup_failed')
    result = run_process([str(executable), str(WORKER), 'versions'], timeout=30, env=env)
    manifest = json.loads(result.stdout)
    if result.returncode or manifest['docling'] != VERSION:
        return failed('runtime_version_mismatch')
    manifest.update(profile=profile, models=[dict(path=p.relative_to(base / 'models').as_posix(), size=p.stat().st_size)
                                            for p in sorted((base / 'models').rglob('*')) if p.is_file()])
    (base / 'environment.json').write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    return doctor(root)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path.cwd())
    sub = parser.add_subparsers(dest='command', required=True)
    install = sub.add_parser('setup')
    install.add_argument('--profile', choices=['documents'], default='documents')
    install.add_argument('--json', action='store_true')
    sub.add_parser('doctor').add_argument('--json', action='store_true')
    args = parser.parse_args()
    try:
        if args.command == 'setup':
            print('Installing project-local Docling 2.132.0, layout, tables and Latin OCR models.', file=sys.stderr)
            result = setup(args.root, args.profile)
        else:
            result = doctor(args.root)
    except (OSError, ValueError, subprocess.SubprocessError):
        result = failed('storage_or_runtime_check_failed')
    print(json.dumps(result, ensure_ascii=False))
    return 0 if result['state'] == 'ready' else 1


if __name__ == '__main__':
    raise SystemExit(main())
